# Import Initial Dependencies

In [1]:
from tickers import Ticker, scrape_tickers, query_list, recent_IPO_list, upcoming_IPO_list
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer as SIA
from pprint import pprint

In [2]:
#nltk.download("stopwords")
#nltk.download('punkt')
#nltk.download('vader_lexicon')

# Load Data

In [3]:
# Scrape to get updated tickers and company names for stocks and ETFs
scrape_tickers()

import_lists = [query_list, recent_IPO_list, upcoming_IPO_list]

tickers = []

# Build raw query list with ticker abbrevation and name of company
for i in import_lists:
    for item in i:
        tickers.append(item)

In [4]:
# Load in data for testing - will be replace with dataframes when in production
submissions_df = pd.read_csv('submissions.csv')
comments_df = pd.read_csv('comments.csv')

# Data Pre-Processing

### Remove Non-Alphanumeric Characters

In [7]:
import re
 
def scrub_data(text):
    clean = re.sub(r'[^A-Za-z0-9 ]+', '', text)
    return clean

In [8]:
# Clean submission body and title
submissions_df["Clean_Body"] = submissions_df.Body.apply(scrub_data)
submissions_df["Clean_Title"] = submissions_df.Title.apply(scrub_data)

In [9]:
# Clean comments
comments_df["Clean_Body"] = comments_df.Body.apply(scrub_data)

### Tokenize Data

In [10]:
# Create Function to Handle Errors During Tokenization
def tokenize_text(text):
    if not text:
        print("Text cannot be tokenize due to type errors.")
        text = ""
    text = text.lower()
    return nltk.word_tokenize(text)

In [11]:
# Tokenize submission body and title
submissions_df["Body_Tokens"] = submissions_df.Clean_Body.apply(tokenize_text)
submissions_df["Title_Tokens"] = submissions_df.Clean_Title.apply(tokenize_text)

In [12]:
# Tokenize comments
comments_df["Body_Tokens"] = comments_df.Clean_Body.apply(tokenize_text)

Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to type errors.
Text cannot be tokenize due to t

### Remove stop words

In [13]:
# Remove defined stop words from company names to prevent inaccurate labeling
common_words = ['Corp', 'Corporation', 'Ltd', 'Acquisition', 'Pharmaceuticals', 'Holding', 'Group']
new_name = ""
ticker_names = []
for ticker in tickers:
    new_name = ""
    company_words = ticker.name.split()
    for word in company_words:
        if word in common_words:
            continue
        else:
            if new_name == "":
                new_name = word
            else:
                new_name = new_name + " " + word
    ticker.name = new_name

In [14]:
stop_words = list(set(stopwords.words("english")))
def remove_stop_words(text):
    if not text:
        print("Type errors.")
        text = ""
    return [w for w in text if w not in stop_words]

In [15]:
submissions_df["Clean_Body_Tokens"] = submissions_df.Body_Tokens.apply(remove_stop_words)
submissions_df["Clean_Title_Tokens"] = submissions_df.Title_Tokens.apply(remove_stop_words)

In [16]:
# Create TF-IDF matrix using SciKit-Learn
#from sklearn.feature_extraction.text import TfidfVectorizer
# Create instance of Vectorizer
#vectorizer = TfidfVectorizer()
#tfidf = vectorizer.fit_transform(submissions_tokens)

In [17]:
# convert sentences to array of words
#submissions_df['Body_Words'] = submissions_df.Body.str.replace("'", "").str.strip().str.split('[\W_]+')
#submissions_df['Title_Words'] = submissions_df.Title.str.replace("'", "").str.strip().str.split('[\W_]+')

### Find Tickers Mentioned

In [18]:
# Tag all tickers found in array of words for each post
submissions_df["Tickers"] = ""

def tokenize_tickers(text):
    if not text:
        print("Text cannot be tokenize due to type errors.")
        text = ""
    return nltk.word_tokenize(text)

for index, row in submissions_df.iterrows():
    body = row[4]
    title = row[2]
    body_tokens = tokenize_tickers(body)
    title_tokens = tokenize_tickers(title)
    tickers_found = []
    body_set = set(body_tokens)
    title_set = set(title_tokens)
    for ticker in tickers:
        if ticker.abbrev == 'A' or ticker.abbrev == 'I':
            if (ticker.name in body_set) or (ticker.name in title_set):
                tickers_found.append(ticker.abbrev)
        else:
            if (ticker.abbrev in body_set) or (ticker.abbrev in title_set):
                if ticker.abbrev not in tickers_found:
                    tickers_found.append(ticker.abbrev)
            elif (ticker.name in body_set) or (ticker.name in title_set):
                if ticker.abbrev not in tickers_found:
                    tickers_found.append(ticker.abbrev)
    if len(tickers_found) == 0:
        submissions_df.at[index, "Tickers"] = ""
    else:
        submissions_df.at[index, "Tickers"]= tickers_found

In [19]:
submissions_df

Post_Type Submission_ID  \
0    Submission        n7eybf   
1    Submission        nqk7qi   
2    Submission        n9a2nc   
3    Submission        nanrlu   
4    Submission        nrou4z   
..          ...           ...   
995  Submission        n98qqa   
996  Submission        n93thn   
997  Submission        n7yug8   
998  Submission        n7rqy5   
999  Submission        n7bqw5   

                                                 Title           Author  \
0    96% of US users opt out of app tracking in iOS...           Karnes   
1    AMC to Offer Free Popcorn and Exclusive Screen...  rgujjula-csdude   
2    Chipotle to hike wages, debut referral bonuses...     Brothanogood   
3    I analyzed 9000+ trades made by Members of the...           nobjos   
4    With wood prices so high, curiosity struck me....    chumbawamba56   
..                                                 ...              ...   
995      Arbitrage opportunity with 6 months timeframe         vasesimi   
996  Gasoline prices in relation to futures with on...       AIONisMINE   
997       Anyone has an HSA account where they invest?      Dowdell2008   
998                   How to buy stocks like Curaleaf?   Sevendevils777   
999                     The perfect portfolio anxiety.      shortyafter   

                                                  Body                Flair  \
0    "It seems that in the United States, at least,...  Industry Discussion   
1    Full Article Here: [https://www.cnbc.com/2021/...                  NaN   
2    Chipotle said it will increase restaurant wage...         Company News   
3    **Preamble:** The ability of Congress to trade...                 Meta   
4    Wood is crazy expensive right now. and most se...     Company Analysis   
..                                                 ...                  ...   
995   \n\nHi all,\n\nI've been a lurker and got som...         Company News   
996  I dont follow oil stock. Much less futures in ...                  NaN   
997  I guess the title says it all. I have one but ...                  NaN   
998  I’m having difficulty being able to find platf...       Advice Request   
999  ***TL;DR*** *- The anxiety that comes with put...                  NaN   

     Distinguished  Num_Comments    Post_ID  \
0              NaN          1635  t3_n7eybf   
1              NaN          1009  t3_nqk7qi   
2              NaN          1665  t3_n9a2nc   
3              NaN           369  t3_nanrlu   
4              NaN          1037  t3_nrou4z   
..             ...           ...        ...   
995            NaN            24  t3_n98qqa   
996            NaN             1  t3_n93thn   
997            NaN            20  t3_n7yug8   
998            NaN            23  t3_n7rqy5   
999            NaN            15  t3_n7bqw5   

                                                   URL  Score  Upvote_Ratio  \
0    https://www.reddit.com/r/stocks/comments/n7eyb...  14318          0.97   
1    https://www.reddit.com/r/stocks/comments/nqk7q...  13764          0.92   
2    https://www.reddit.com/r/stocks/comments/n9a2n...  12772          0.95   
3    https://www.reddit.com/r/stocks/comments/nanrl...   7970          0.97   
4    https://www.reddit.com/r/stocks/comments/nrou4...   5330          0.95   
..                                                 ...    ...           ...   
995  https://www.reddit.com/r/stocks/comments/n98qq...      4          0.67   
996  https://www.reddit.com/r/stocks/comments/n93th...      5          0.73   
997  https://www.reddit.com/r/stocks/comments/n7yug...      5          0.78   
998  https://www.reddit.com/r/stocks/comments/n7rqy...      7          0.74   
999  https://www.reddit.com/r/stocks/comments/n7bqw...      3          0.62   

    Created_Date_UTC                                         Clean_Body  \
0     [1620439925.0]  It seems that in the United States at least ap...   
1     [1622635400.0]  Full Article Here httpswwwcnbccom20210602amcpl...   
2     [1620665963.0]

In [20]:
# Remove submissions without any mention of tickers - unable to interpret relevancy of sentiment
submissions_df = submissions_df.loc[submissions_df['Tickers'] != ""]

In [22]:
#comments_df['Tickers'] = ""
#for index_c, row_c in comments_df.iterrows():
    #for index_s, row_s in submissions_df.iterrows():
        #if row_c[1] == row_s[1]:
             #comments_df.at[index_c, 'Tickers'] = row_s[19]

In [23]:
#comments_df = comments_df.loc[comments_df["Tickers"] != ""]

# Perform Sentiment Analysis Using NLTK

In [24]:
# Create function to perform sentiment analysis
def sent_analyzer(df, body_index, title_index = None, upvote_score_index = None):
    sia = SIA()
    results = []
    df['negative_score'] = ""
    df['neutral_score'] = ""
    df['positive_score'] = ""
    df['compound_score'] = ""
    df['sentiment_label'] = 0
    for index, row in df.iterrows():
        body = row[body_index]
        if title_index is not None:
            title = row[title_index]
            eval_text = title + " " + body
        else:
            eval_text = body
        pol_score= sia.polarity_scores(eval_text)
        df.at[index, 'negative_score'] = pol_score['neg']
        df.at[index, 'neutral_score'] = pol_score['neu']
        df.at[index, 'positive_score'] = pol_score['pos']
        df.at[index, 'compound_score'] = pol_score['compound']
        if upvote_score_index is not None:
            weighted_compound = row[upvote_score_index] * pol_score['compound']
            if weighted_compound > 0.2:
                df.at[index,'sentiment_label'] = 1
            elif weighted_compound < 0.2:
                df.at[index,'sentiment_label'] = -1
            else:
                df.at[index,'sentiment_label'] = 0
        else:
            if pol_score['compound'] > 0.2:
                df.at[index,'sentiment_label'] = 1
            elif pol_score['compound'] < 0.2:
                df.at[index,'sentiment_label'] = -1
            else:
                df.at[index,'sentiment_label'] = 0
    return df

In [25]:
sent_analyzer(submissions_df, 13, 14, 11)

/Users/madisonleopold/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/madisonleopold/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/Users/madisonleopold/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try usin

Post_Type Submission_ID  \
0    Submission        n7eybf   
1    Submission        nqk7qi   
2    Submission        n9a2nc   
3    Submission        nanrlu   
4    Submission        nrou4z   
..          ...           ...   
992  Submission        na2jnb   
993  Submission        na0826   
994  Submission        n9i81t   
997  Submission        n7yug8   
999  Submission        n7bqw5   

                                                 Title               Author  \
0    96% of US users opt out of app tracking in iOS...               Karnes   
1    AMC to Offer Free Popcorn and Exclusive Screen...      rgujjula-csdude   
2    Chipotle to hike wages, debut referral bonuses...         Brothanogood   
3    I analyzed 9000+ trades made by Members of the...               nobjos   
4    With wood prices so high, curiosity struck me....        chumbawamba56   
..                                                 ...                  ...   
992                      Mattel options short interest        QuantumVibing   
993                                 Wash Sale question  PosterOfStinkyShits   
994  Where can I get real time quotes and charts fo...            Virus4762   
997       Anyone has an HSA account where they invest?          Dowdell2008   
999                     The perfect portfolio anxiety.          shortyafter   

                                                  Body                Flair  \
0    "It seems that in the United States, at least,...  Industry Discussion   
1    Full Article Here: [https://www.cnbc.com/2021/...                  NaN   
2    Chipotle said it will increase restaurant wage...         Company News   
3    **Preamble:** The ability of Congress to trade...                 Meta   
4    Wood is crazy expensive right now. and most se...     Company Analysis   
..                                                 ...                  ...   
992  I just noticed on E\*trade that open interest ...                  NaN   
993  So I’m pretty dang new to trading, this mornin...                  NaN   
994  I know that pretty much every broker has live ...                  NaN   
997  I guess the title says it all. I have one but ...                  NaN   
999  ***TL;DR*** *- The anxiety that comes with put...                  NaN   

     Distinguished  Num_Comments    Post_ID  \
0              NaN          1635  t3_n7eybf   
1              NaN          1009  t3_nqk7qi   
2              NaN          1665  t3_n9a2nc   
3              NaN           369  t3_nanrlu   
4              NaN          1037  t3_nrou4z   
..             ...           ...        ...   
992            NaN             9  t3_na2jnb   
993            NaN             4  t3_na0826   
994            NaN             3  t3_n9i81t   
997            NaN            20  t3_n7yug8   
999            NaN            15  t3_n7bqw5   

                                                   URL  ...  \
0    https://www.reddit.com/r/stocks/comments/n7eyb...  ...   
1    https://www.reddit.com/r/stocks/comments/nqk7q...  ...   
2    https://www.reddit.com/r/stocks/comments/n9a2n...  ...   
3    https://www.reddit.com/r/stocks/comments/nanrl...  ...   
4    https://www.reddit.com/r/stocks/comments/nrou4...  ...   
..                                                 ...  ...   
992  https://www.reddit.com/r/stocks/comments/na2jn...  ...   
993  https://www.reddit.com/r/stocks/comments/na082...  ...   
994  https://www.reddit.com/r/stocks/comments/n9i81...  ...   
997  https://www.reddit.com/r/stocks/comments/n7yug...  ...   
999  https://www.reddit.com/r/stocks/comments/n7bqw...  ...   

                                           Body_Tokens  \
0    [it, seems, that, in, the, united, states, at,...   
1    [full, article, here, httpswwwcnbccom20210602a...   
2    [chipotle, said, it, will, increase, restauran...   
3    [preamble, the, ability, of, congress, to, tra...   
4    [wood, is, crazy, expensive, right, now, and, ...   
..                                       

In [26]:
#sent_analyzer(comments_df, 5)

# Split Data into Training and Test Sets

In [27]:
#submissions_sentiment = submissions_df[["Body", "Title", "sentiment_label"]]
submissions_sentiment = submissions_df[["Clean_Body", "Clean_Title", "sentiment_label"]]

In [28]:
#comment_sentiment = comments_df[["Body", "sentiment_label"]]

In [29]:
#dataset = submissions_df[["Body", "Title", "sentiment_label"]]
dataset = submissions_sentiment

In [30]:
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1].values

In [31]:
X_arr = []
for index, row in X.iterrows():
    X_arr.append(row.values)

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_arr, y, test_size = 0.2, random_state = 0)

In [33]:
X_train

[array(['I started really investing this year and looking for long term holdings After about 5 months or so I have decided to start putting money into ETFs for the time being while I research and learn about companies more For ETFs Im thinking about are the followingVOOQQQIm looking for another ETF that is not apart of Tech to kind of help diversify my holdings I was wondering if XLC would be a good third ETF My plan right now is each month put X amount into a single ETF then the next month put it into the next ETF etc and essentially continously put money into all three ETFs Im in my late 20s and my goal is to hold long term 10  15 years or longer If anyone has suggestions on other ETFs I would greatly appreciate it as Im trying to find the right ETFs to get into and hopefully grow over timeThank you in advance',
        'What 3 ETFs are good to diversify with and buy into'],
       dtype=object),
 array(['Ive been into Hydrogen for quite a while and I think APD is severely undervalue

# Bag of Words Vectorization

In [34]:
def identity_tokenizer(text):
    return text

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(tokenizer=identity_tokenizer, lowercase=False)

# fit AND transform the model (only for training data)
X_train_vectors = vectorizer.fit_transform(X_train)

# transform the test data
X_test_vectors = vectorizer.transform(X_test)

In [36]:
# Review data ouput
print(X_train_vectors.toarray())
print(X_train[0])
print(X_train_vectors[0])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['I started really investing this year and looking for long term holdings After about 5 months or so I have decided to start putting money into ETFs for the time being while I research and learn about companies more For ETFs Im thinking about are the followingVOOQQQIm looking for another ETF that is not apart of Tech to kind of help diversify my holdings I was wondering if XLC would be a good third ETF My plan right now is each month put X amount into a single ETF then the next month put it into the next ETF etc and essentially continously put money into all three ETFs Im in my late 20s and my goal is to hold long term 10  15 years or longer If anyone has suggestions on other ETFs I would greatly appreciate it as Im trying to find the right ETFs to get into and hopefully grow over timeThank you in advance'
 'What 3 ETFs are good to diversify with and buy into']
  (0, 

# Train Several Models with Training Set

In [37]:
# Linear SVM

from sklearn import svm

clf_svm = svm.SVC(kernel="linear")

clf_svm.fit(X_train_vectors, y_train)

SVC(kernel='linear')

In [38]:
clf_svm_pred = clf_svm.predict(X_test_vectors)

In [39]:
#Analyze some predictions
print(X_test[3])
print(clf_svm_pred[3])

['I own REMX since someyears ago Its expense ratio is higher than what I think is ideal for alongterm accumulation 510 of total portfolio Does anyone here have a suggestion about a similar ETF with lower ER'
 'Any suggetions on a rare earth ETF similar to REMX']
1


In [40]:
# Evaluate Model Accuracy
from sklearn.metrics import accuracy_score

accuracy_score(y_test, clf_svm_pred)

0.863013698630137

In [41]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier

clf_dec = DecisionTreeClassifier()

clf_dec.fit(X_train_vectors, y_train)

DecisionTreeClassifier()

In [42]:
clf_dec_pred = clf_dec.predict(X_test_vectors)

In [43]:
#Analyze some predictions
print(X_test[3])
print(clf_dec_pred[3])

['I own REMX since someyears ago Its expense ratio is higher than what I think is ideal for alongterm accumulation 510 of total portfolio Does anyone here have a suggestion about a similar ETF with lower ER'
 'Any suggetions on a rare earth ETF similar to REMX']
1


In [44]:
# Evaluate Model Accuracy
accuracy_score(y_test, clf_dec_pred)

0.863013698630137

In [45]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

clf_gnb = DecisionTreeClassifier()
clf_gnb.fit(X_train_vectors, y_train)

clf_gnb_pred = clf_gnb.predict(X_test_vectors)

In [46]:
# Evaluate Model Accuracy
accuracy_score(y_test, clf_gnb_pred)

0.863013698630137

In [ ]:
#combined_df = submissions_df.join(sentiment_average)
combined_df = pd.merge(submissions_df, sentiment_average, how='left', on='Submission_ID',
         left_index=False, right_index=False, sort=True,
         suffixes=('_x', '_y'), copy=True, indicator=False,
         validate=None)

In [ ]:
ticker_sentiment = pd.DataFrame()

In [ ]:
ticker_sentiment["Ticker"] = ""
ticker_sentiment["Total_Count"] = 0
ticker_sentiment["Total_Sentiment"] = 0

In [ ]:
index = 0
for ticker in tickers:
    ticker_sentiment.at[index, "Ticker"] = ticker.abbrev
    ticker_sentiment.at[index, "Total_Count"] = 0
    ticker_sentiment.at[index, "Total_Sentiment"] = 0
    index += 1

In [ ]:
submissions_df['sentiment_weight'] = submissions_df['Score'] * submissions_df['Upvote_Ratio']

In [ ]:
ticker_sentiment = ticker_sentiment.drop_duplicates(subset=['Ticker'])

In [ ]:
ticker_sentiment

In [ ]:
# Get running count of tickers mentioned (# of times mentioned) and with average sentiment
for index, row in ticker_sentiment.iterrows():
    ticker_abbrev = row[0]
    total_count = row[1]
    total_sentiment = row[2]
    for i, r in combined_df.iterrows():
        # Get column with tickers found
        ticker_set = set(r[15])
        post_sentiment = r[26]
        if ticker_abbrev in ticker_set:
            total_count += 1
            total_sentiment += post_sentiment
    ticker_sentiment.at[index, "Total_Count"] = total_count
    ticker_sentiment.at[index, "Total_Sentiment"] = total_sentiment

In [ ]:
final_sentiment_results = ticker_sentiment.loc[ticker_sentiment['Total_Count'] != 0]

In [ ]:
final_sentiment_results = final_sentiment_results.reset_index(drop=True)

In [ ]:
final_sentiment_results

In [ ]:
final_sentiment_results["Average_Sentiment"] = final_sentiment_results["Total_Count"] / final_sentiment_results["Total_Sentiment"]

In [ ]:
final_sentiment_results

In [ ]:
final_sentiment_results['Average_Sentiment'].unique()

In [ ]:
final_sentiment_results['sentiment_label'] = "Neutral"
final_sentiment_results.loc[final_sentiment_results['Average_Sentiment'] > 0.2, 'sentiment_label'] = "Bullish"
final_sentiment_results.loc[final_sentiment_results['Average_Sentiment'] < -0.2, 'sentiment_label'] = "Bearish"

In [ ]:
# Add "today's price change" to each ticker found - total count, average sentiment, today's price change
# Include graph for visuals
import yfinance as yf
from datetime import date

In [ ]:
todays_date = date.today()
todays_date

In [ ]:
final_sentiment_results["Price_Change"] = ""
final_sentiment_results["Date"] = ""
for index, row in final_sentiment_results.iterrows():
    try:
        df = yf.download(row[0], start=todays_date)
        date = df.index[0]
        close_price = df["Close"].values[0]
        open_price = df["Open"].values[0]
        percentage_change = round((((close_price - open_price) / open_price) * 100), 2)
        final_sentiment_results.at[index, "Price_Change"] = f'{percentage_change}%'
        final_sentiment_results.at[index, "Date"] = date
    except:
        print("Data not found")
        final_sentiment_results.at[index, "Price_Change"] = "Ticker unavailable"
        final_sentiment_results.at[index, "Date"] = date

In [ ]:
final_sentiment_results

# Test database connection and process

In [ ]:
# Import SQL Alchemy
from sqlalchemy import create_engine

# Import datetime
from datetime import datetime

# Import and establish Base for which classes will be constructed 
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, Float

In [ ]:
# Create the Ticker Sentiment class
class Ticker_Sentiment(Base):
    __tablename__ = 'ticker_sentiment'
    id = Column(Integer, primary_key=True)
    ticker = Column(String(255))
    date = Column(String(255))
    count = Column(Integer)
    sentiment = Column(String)
    percent_change = Column(Float)

In [ ]:
# Create a connection to a SQLite database
engine = create_engine('sqlite:///reddit_sentiment.db')

In [ ]:
# Create the ticker_sentiment table within the database
Base.metadata.create_all(engine)

In [ ]:
# Push the objects made and query the server
from sqlalchemy.orm import Session
session = Session(bind=engine)

In [ ]:
sql_df = final_sentiment_results[["Ticker", "Date", "Total_Count", "sentiment_label", "Price_Change"]]

In [ ]:
sql_df = sql_df.rename(columns={"Ticker":"ticker", "Date":"date", "Total_Count":"count", "sentiment_label":"sentiment", "Price_Change":"percent_change"})

In [ ]:
sql_df

In [ ]:
sql_df.to_sql('ticker_sentiment', con=engine, if_exists='append', index=False)

In [ ]:
from sqlalchemy.ext.automap import automap_base
# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save reference to the table
sentiment = Base.classes.ticker_sentiment

In [ ]:
session = Session(engine)

results = session.query(sentiment.ticker).all()

session.close()

In [ ]:
import numpy as np
sentiment = list(np.ravel(results))

In [ ]:
print(sentiment)