# Import Initial Dependencies

In [1]:
from tickers import Ticker, scrape_tickers, query_list, recent_IPO_list, upcoming_IPO_list
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer as SIA
from pprint import pprint

In [2]:
#nltk.download("stopwords")
#nltk.download('punkt')
#nltk.download('vader_lexicon')

# Load Data

In [3]:
# Scrape to get updated tickers and company names for stocks and ETFs
scrape_tickers()

import_lists = [query_list, recent_IPO_list, upcoming_IPO_list]

tickers = []

# Build raw query list with ticker abbrevation and name of company
for i in import_lists:
    for item in i:
        tickers.append(item)

In [21]:
# Load in data for testing - will be replace with dataframes when in production
submissions_df = pd.read_csv('submissions.csv')
comments_df = pd.read_csv('comments.csv')

# Data Pre-Processing

### Tokenize Data

In [5]:
# Create Function to Handle Errors During Tokenization
def tokenize_text(text):
    if not text:
        print("Text cannot be tokenize due to type errors.")
        text = ""
    return nltk.word_tokenize(text)

In [22]:
# Tokenize submission body and title
submissions_df["Body_Tokens"] = submissions_df.Body.apply(tokenize_text)
submissions_df["Title_Tokens"] = submissions_df.Title.apply(tokenize_text)

In [23]:
# Tokenize comments
comments_df["Body_Tokens"] = comments_df.Body.apply(tokenize_text)

### Remove stop words

In [8]:
# Remove defined stop words from company names to prevent inaccurate labeling
common_words = ['Corp', 'Corporation', 'Ltd', 'Acquisition', 'Pharmaceuticals', 'Holding', 'Group']
new_name = ""
ticker_names = []
for ticker in tickers:
    new_name = ""
    company_words = ticker.name.split()
    for word in company_words:
        if word in common_words:
            continue
        else:
            if new_name == "":
                new_name = word
            else:
                new_name = new_name + " " + word
    ticker.name = new_name

In [ ]:
#stop_words = list(set(stopwords.words("english")))
#body_tokens = submissions_df["Body_Tokens"]
#filtered_body_tokens = []
 
#for w in body_tokens:
    #if w not in stop_words:
       # filtered_body_tokens.append(w)

In [ ]:
# Create TF-IDF matrix using SciKit-Learn
#from sklearn.feature_extraction.text import TfidfVectorizer
# Create instance of Vectorizer
#vectorizer = TfidfVectorizer()
#tfidf = vectorizer.fit_transform(submissions_tokens)

In [ ]:
# convert sentences to array of words
#submissions_df['Body_Words'] = submissions_df.Body.str.replace("'", "").str.strip().str.split('[\W_]+')
#submissions_df['Title_Words'] = submissions_df.Title.str.replace("'", "").str.strip().str.split('[\W_]+')

### Find Tickers Mentioned

In [24]:
# Tag all tickers found in array of words for each post
submissions_df["Tickers"] = ""
for index, row in submissions_df.iterrows():
    body_tokens = row[13]
    title_tokens = row[14]
    tickers_found = []
    body_set = set(body_tokens)
    title_set = set(title_tokens)
    for ticker in tickers:
        if ticker.abbrev == 'A' or ticker.abbrev == 'I':
            if (ticker.name in body_set) or (ticker.name in title_set):
                tickers_found.append(ticker.abbrev)
        else:
            if (ticker.abbrev in body_set) or (ticker.abbrev in title_set):
                if ticker.abbrev not in tickers_found:
                    tickers_found.append(ticker.abbrev)
            elif (ticker.name in body_set) or (ticker.name in title_set):
                if ticker.abbrev not in tickers_found:
                    tickers_found.append(ticker.abbrev)
    if len(tickers_found) == 0:
        submissions_df.at[index, "Tickers"] = ""
    else:
        submissions_df.at[index, "Tickers"]= tickers_found

In [25]:
# Remove submissions without any mention of tickers - unable to interpret relevancy of sentiment
submissions_df = submissions_df.loc[submissions_df['Tickers'] != ""]

In [36]:
comments_df['Tickers'] = ""
for index_c, row_c in comments_df.iterrows():
    for index_s, row_s in submissions_df.iterrows():
        if row_c[1] == row_s[1]:
             comments_df.at[index_c, 'Tickers'] = row_s[15]

In [37]:
comments_df = comments_df.loc[comments_df["Tickers"] != ""]

# Perform Sentiment Analysis Using NLTK

In [33]:
# Create function to perform sentiment analysis
def sent_analyzer(df, body_index, title_index = None):
    sia = SIA()
    results = []
    df['negative_score'] = ""
    df['neutral_score'] = ""
    df['positive_score'] = ""
    df['compound_score'] = ""
    df['sentiment_label'] = 0
    for index, row in df.iterrows():
        body = row[body_index]
        if title_index is not None:
            title = row[title_index]
            eval_text = title + " " + body
        else:
            eval_text = body
        pol_score= sia.polarity_scores(eval_text)
        df.at[index, 'negative_score'] = pol_score['neg']
        df.at[index, 'neutral_score'] = pol_score['neu']
        df.at[index, 'positive_score'] = pol_score['pos']
        df.at[index, 'compound_score'] = pol_score['compound']
        if pol_score['compound'] > 0.2:
            df.at[index,'sentiment_label'] = 1
        elif pol_score['compound'] < 0.2:
            df.at[index,'sentiment_label'] = -1
        else:
            df.at[index,'sentiment_label'] = 0
    return df

In [34]:
sent_analyzer(submissions_df, 4, 2)

Post_Type Submission_ID  \
1   Submission        me2d54   
2   Submission        me8kb3   
3   Submission        me1wx4   
4   Submission        med6uw   
6   Submission        mdwibp   
7   Submission        mdvvkm   
10  Submission        me0ast   
11  Submission        mebzea   
12  Submission        mdtss5   
13  Submission        meaofc   
14  Submission        me400c   
15  Submission        mdt1eq   
16  Submission        me6ri7   
17  Submission        me09qn   
19  Submission        me2ira   
20  Submission        mdzpaw   
21  Submission        mdrxmt   
22  Submission        mdvdyu   
23  Submission        mds4bo   
28  Submission        mdxeu8   
29  Submission        mdrf39   
30  Submission        mec5yn   
31  Submission        me1ogw   
32  Submission        meb9bp   
34  Submission        mdztbf   
36  Submission        mdudo6   
38  Submission        mdr73u   
39  Submission        mdzyga   
41  Submission        meeklg   
42  Submission        mee0g9   
44  Submission        mdvvx8   
45  Submission        mdssz4   
46  Submission        mdsfjo   
48  Submission        med9ls   
49  Submission        mead8w   
50  Submission        mea57x   
51  Submission        me2nv7   
52  Submission        mdxeba   
53  Submission        mdvfka   
54  Submission        mdv4h8   
56  Submission        mdqmi5   
57  Submission        med1cc   
59  Submission        mdy17k   
62  Submission        mds0i6   
64  Submission        me41f4   
65  Submission        me37ft   
66  Submission        me2yul   
67  Submission        me9zg9   
68  Submission        me5cw4   
69  Submission        mdrs63   
70  Submission        mdz868   
71  Submission        mdrafp   
72  Submission        me11cn   

                                                Title                Author  \
1   Here is a Market Recap for today Friday, March...        psychotrader00   
2   5 Considerations When Picking Stocks for Long-...        MinnesotaPower   
3   I believe two contradictory things about stock...     NotLegallyBinding   
4   Wall Street Week Ahead for the trading week be...           bigbear0083   
6   PLTR - bearish discussion to better understand...         wsbloverrrrrr   
7   Opportunity to gain about 10-14% on $MX (Bough...           RowanHarley   
10  Some figures summarizing what has been happeni...           futureIsYes   
11     What stocks focus on sexual self-satisfaction?                 Smur_   
12                     Anyone own Viacom (VIAC) here?        rockinoutwith2   
13                             Suez Canal Tanker Play          TimThyTurtle   
14                             ARKK options purchases           Lurky_Water   
15           [Nio vs F] Why is NIO more hyped than F?    Many_Artichoke9463   
16                                  Canal Opportunity           Oshititsale   
17    REIT Portfolio to hold in my Retirement account             danielfc_   
19  Globe and Mail: The backing of German governme...               Torlek1   
20                             How could this happen?         FitSkirtShirt   
21  Merck’s (MRK) Brown Pill Could Transform the F...             kaboom987   
22  [DD] Why the GME dream to have retail to funda...               dwpunch   
23            Anyone Else Getting Bearish on Midcaps?          JagwarRocker   
28                                 CP Rail KCS Merger            justgotone   
29              Rookie Mistake, left with a question.       Cindermidnight2   
30                        Nasdaq's battle with 13,000            nycliving1   
31  Any way to test my investment thesis systemati...             fadisaleh   
32  Wondering why some stocks have been taking a u...                one8e4   
34  Did something happen to Crwd(Crowd strike) tha...               Galion-   
36  Looking for ETF recommendations to round out p...           villikrilli   
38  Short term tanker stocks for Suez Canal blocka...     Rock_it_Scientist   
39  Experiment: Selling Covered Calls as a Way of ...           

In [38]:
sent_analyzer(comments_df, 5)

Post_Type Submission_ID Comment_ID   Parent_ID                Author  \
187    Comment        me2d54    gsd1r54   t3_me2d54                 pman6   
188    Comment        me2d54    gsdbbya   t3_me2d54             NeelAsman   
189    Comment        me2d54    gsd2vy0   t3_me2d54          thatsjetfuel   
190    Comment        me2d54    gsd61xo  t1_gsd1r54             hitmon_gg   
191    Comment        me2d54    gsddp75  t1_gsd1r54             bothodler   
...        ...           ...        ...         ...                   ...   
2111   Comment        me11cn    gsdhaar  t1_gsdf2zh          merlinsbeers   
2112   Comment        me11cn    gsge5va  t1_gsdf2zh  harrison_wintergreen   
2113   Comment        me11cn    gsd6jo3  t1_gscuc3i             Ironleg01   
2114   Comment        me11cn    gsd0mbr  t1_gsczs3d            Tacoman404   
2115   Comment        me11cn    gsdid8c  t1_gsdhaar                mimo_s   

                                                   Body  Flair Distinguished  \
187   ['ok guys....\n\nwhat the fuck happened during...    NaN           NaN   
188   ['Shout out for yesterday’s post, you nailed S...    NaN           NaN   
189   ["I'm not seeing how TSM is a bad play at this...    NaN           NaN   
190         ['God wanted me to have a better weekend?']    NaN           NaN   
191   ["I don't want to get super conspiracy-ie but ...    NaN           NaN   
...                                                 ...    ...           ...   
2111  ["He isn't self-made. He comes from a wealthy ...    NaN           NaN   
2112  ['> That dude is one of the few self made bill...    NaN           NaN   
2113  ['Oh wow, news outlet reporting on thing that ...    NaN           NaN   
2114             ['Huh, Elon Musk is actually a vole?']    NaN           NaN   
2115  ['They didn’t mention his brother in the book ...    NaN           NaN   

      Is_Author  Score Created_Date_UTC  \
187       False     35   [1616805654.0]   
188       False      5   [1616809931.0]   
189       False      7   [1616806145.0]   
190       False     23   [1616807556.0]   
191       False     10   [1616811018.0]   
...         ...    ...              ...   
2111      False      2   [1616812668.0]   
2112      False      1   [1616856792.0]   
2113      False      4   [1616807785.0]   
2114      False      2   [1616805158.0]   
2115      False      3   [1616813203.0]   

                                            Body_Tokens  \
187   [[, 'ok, guys, ...., \n\nwhat, the, fuck, happ...   
188   [[, 'Shout, out, for, yesterday, ’, s, post, ,...   
189   [[, ``, I, 'm, not, seeing, how, TSM, is, a, b...   
190   [[, 'God, wanted, me, to, have, a, better, wee...   
191   [[, ``, I, do, n't, want, to, get, super, cons...   
...                                                 ...   
2111  [[, ``, He, is, n't, self-made, ., He, comes, ...   
2112  [[, ', >, That, dude, is, one, of, the, few, s...   
2113  [[, 'Oh, wow, ,, news, outlet, reporting, on, ...   
2114  [[, 'Huh, ,, Elon, Musk, is, actually, a, vole...   
2115  [[, 'They, didn, ’, t, mention, his, brother, ...   

                                                Tickers negative_score  \
187   [ADS, BCS, DRI, HON, JP, MS, NDAQ, NIO, ORLY, ...          0.224   
188   [ADS, BCS, DRI, HON, JP, MS, NDAQ, NIO, ORLY, ...              0   
189   [ADS, BCS, DRI, HON, JP, MS, NDAQ, NIO, ORLY, ...          0.147   
190   [ADS, BCS, DRI, HON, JP, MS, NDAQ, NIO, ORLY, ...              0   
191   [ADS, BCS, DRI, HON, JP, MS, NDAQ, NIO, ORLY, ...          0.299   
...                                                 ...            ...   
2111                                   [ARK, CEO, TSLA]              0   
2112                                   [ARK, CEO, TSLA]              0   
2113                                   [ARK, CEO, TSLA]          0.296   
2114                                   [ARK, CEO, TSLA]              0   
2115                                   [ARK, CEO, TSLA]              0   

    

# Split Data into Training and Test Sets

In [91]:
dataset = submissions_df[["Body", "Title", "sentiment_label"]]

In [94]:
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1].values

In [100]:
X_arr = []
for index, row in X.iterrows():
    X_arr.append(row.values)

In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_arr, y, test_size = 0.2, random_state = 0)

In [107]:
X_train

[array(['“The ARKK Trades: At 2:09 p.m. Thursday a trader executed a put sweep of 7,238 ARKK options with a $100 strike price expiring April 16. The trade represented a $38,000 bearish bet for which the trader paid $5.25 per option contract.\n\nAt 1:04 p.m., a trader executed a put sweep of 400 ARKK options with a $110 strike price expiring on Jan. 20, 2023. The trade represented a $1.4-million bearish bet for which the trader paid $26 per option contract.\n\nAt 11:16 p.m., a trader executed a put sweep of 1,500 ARKK options with a $125 strike price expiring May 21. The trade represented a $2.49-million bearish bet for which the trader paid $16.60 per option contract.\n\nAt 11:15 p.m., a trader executed a put sweep of 819 ARKK options with a $100 strike price expiring on May. 21. The trade represented a $1.35-million bearish bet for which the trader paid $16.50 per option contract.\n\nAt 11:15 p.m., a trader executed a put sweep of 1,028 ARKK options with a $125 strike price expiring o

# Bag of Words Vectorization

In [113]:
def identity_tokenizer(text):
    return text

In [115]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(tokenizer=identity_tokenizer, lowercase=False)

# fit AND transform the model (only for training data)
X_train_vectors = vectorizer.fit_transform(X_train)

# transform the test data
X_test_vectors = vectorizer.transform(X_test)

In [119]:
# Review data ouput
print(X_train_vectors.toarray())
print(X_train[0])
print(X_train_vectors[0])

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['“The ARKK Trades: At 2:09 p.m. Thursday a trader executed a put sweep of 7,238 ARKK options with a $100 strike price expiring April 16. The trade represented a $38,000 bearish bet for which the trader paid $5.25 per option contract.\n\nAt 1:04 p.m., a trader executed a put sweep of 400 ARKK options with a $110 strike price expiring on Jan. 20, 2023. The trade represented a $1.4-million bearish bet for which the trader paid $26 per option contract.\n\nAt 11:16 p.m., a trader executed a put sweep of 1,500 ARKK options with a $125 strike price expiring May 21. The trade represented a $2.49-million bearish bet for which the trader paid $16.60 per option contract.\n\nAt 11:15 p.m., a trader executed a put sweep of 819 ARKK options with a $100 strike price expiring on May. 21. The trade represented a $1.35-million bearish bet for which the trader paid $16.50 per option co

# Train Several Models on Training Set

In [120]:
# Linear SVM

from sklearn import svm

clf_svm = svm.SVC(kernel="linear")

clf_svm.fit(X_train_vectors, y_train)

SVC(kernel='linear')

In [121]:
clf_svm_pred = clf_svm.predict(X_test_vectors)

In [126]:
#Analyze some predictions
print(X_test[3])
print(clf_svm_pred[3])

['Good morning investors.\n\nTo cut to the chase I’m at a crossroad. After a massive loss (for me) on GME and AMC, I told myself I need to stay out of stocks for a while. Well, I saved $3,500 to invest and I don’t feel right letting it get dusty in my checking account. Here’s the stocks currently on my list, I’m open for any suggestions.\n(I have separated my allotted money into sections, that’s why some relatively good stocks are at lower number figures)\n\n-$SPY - $600\n-$VUG - $450\n-$APPL - $375\n-$DKNG - $400\n-$CCL - $400\n-$TRIP - $250\n-$WH - $225\n-$SPWR - $200\n-$FSLR - $250\n-$AXP - $350\n\nThese are all meant to be medium term plays. I’m thinking around a year taking profits at my own discretion. \n\nThanks a lot, everybody'
 'Here’s my list, thoughts?']
1


In [127]:
# Evaluate Model Accuracy
clf_svm.score(X_test_vectors, y_test)

0.6363636363636364

In [128]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier

clf_dec = DecisionTreeClassifier()

clf_dec.fit(X_train_vectors, y_train)

DecisionTreeClassifier()

In [129]:
clf_dec_pred = clf_dec.predict(X_test_vectors)

In [130]:
#Analyze some predictions
print(X_test[3])
print(clf_dec_pred[3])

['Good morning investors.\n\nTo cut to the chase I’m at a crossroad. After a massive loss (for me) on GME and AMC, I told myself I need to stay out of stocks for a while. Well, I saved $3,500 to invest and I don’t feel right letting it get dusty in my checking account. Here’s the stocks currently on my list, I’m open for any suggestions.\n(I have separated my allotted money into sections, that’s why some relatively good stocks are at lower number figures)\n\n-$SPY - $600\n-$VUG - $450\n-$APPL - $375\n-$DKNG - $400\n-$CCL - $400\n-$TRIP - $250\n-$WH - $225\n-$SPWR - $200\n-$FSLR - $250\n-$AXP - $350\n\nThese are all meant to be medium term plays. I’m thinking around a year taking profits at my own discretion. \n\nThanks a lot, everybody'
 'Here’s my list, thoughts?']
1


In [131]:
# Evaluate Model Accuracy
clf_dec.score(X_test_vectors, y_test)

0.6363636363636364

In [134]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

clf_gnb = DecisionTreeClassifier()
clf_gnb.fit(X_train_vectors, y_train)

clf_gnb.predict(X_test_vectors)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [135]:
# Evaluate Model Accuracy
clf_gnb.score(X_test_vectors, y_test)

0.6363636363636364

In [ ]:
sentiment_average_df['sentiment_weight'] = comments_df['Score']
sentiment_average_df

In [ ]:
sentiment_average_df['sentiment_adjusted'] = sentiment_average_df['sentiment_label'] * sentiment_average_df['sentiment_weight']

In [ ]:
sentiment_average = sentiment_average_df[['Submission_ID','sentiment_adjusted']].groupby('Submission_ID').mean()

In [ ]:
sentiment_average['sentiment_output'] = 0
sentiment_average.loc[sentiment_average['sentiment_adjusted'] > 0.2, 'sentiment_output'] = 1
sentiment_average.loc[sentiment_average['sentiment_adjusted'] < -0.2, 'sentiment_output'] = -1
sentiment_average.reset_index(inplace=True)
#sentiment_average = sentiment_average.set_index('Submission_ID')

In [ ]:
sentiment_average

In [ ]:
#combined_df = submissions_df.join(sentiment_average)
combined_df = pd.merge(submissions_df, sentiment_average, how='left', on='Submission_ID',
         left_index=False, right_index=False, sort=True,
         suffixes=('_x', '_y'), copy=True, indicator=False,
         validate=None)

In [45]:
# Account for Upvote Ratio to get adjust sentiment
for index, row in submissions_df.iterrows():
    upvote_ratio = row[11]
    sentiment_label = row[18]
    if upvote_ratio <= 0.8:
        if sentiment_label == 1:
            submission_df.at[index, "sentiment_label"] = -1
        elif sentiment_label == -1:
            submission_df.at[index, "sentiment_label"] = 1

0.107
0.12200000000000001
0.081
0.098
0.188
0.152
0.0
0.127
0.165
0.128
0.019
0.09599999999999999
0.176
0.099
0.086
0.072
0.064
0.161
0.04
0.188
0.14999999999999997
0.03900000000000001
0.152
0.0
0.10200000000000001
0.11400000000000002
0.051
0.073
0.0
0.105
0.13
0.049
0.15399999999999997
0.142
0.132
0.131
0.124
0.14
0.178
0.135
0.043000000000000003
0.046
0.10999999999999999
0.203
0.041
0.172
0.146
0.052
0.042
0
0
0
0


In [ ]:
combined_df.rename(columns = {'sentiment_adjusted':'comment_sentiment'}, inplace = True)

In [ ]:
combined_df['submission_sentiment'] = combined_df['sentiment_label'] * combined_df['sentiment_weight']

In [ ]:
combined_df.head()

In [ ]:
combined_df['combined_sentiment'] = combined_df['comment_sentiment'] + combined_df['submission_sentiment']

In [ ]:
combined_df['final_sentiment_label'] = 0
combined_df.loc[combined_df['combined_sentiment'] > 0.2, 'final_sentiment_label'] = 1
combined_df.loc[combined_df['combined_sentiment'] < -0.2, 'final_sentiment_label'] = -1

In [ ]:
ticker_sentiment = pd.DataFrame()

In [ ]:
ticker_sentiment["Ticker"] = ""
ticker_sentiment["Total_Count"] = 0
ticker_sentiment["Total_Sentiment"] = 0

In [ ]:
index = 0
for ticker in tickers:
    ticker_sentiment.at[index, "Ticker"] = ticker.abbrev
    ticker_sentiment.at[index, "Total_Count"] = 0
    ticker_sentiment.at[index, "Total_Sentiment"] = 0
    index += 1

In [ ]:
submissions_df['sentiment_weight'] = submissions_df['Score'] * submissions_df['Upvote_Ratio']

In [ ]:
ticker_sentiment = ticker_sentiment.drop_duplicates(subset=['Ticker'])

In [ ]:
ticker_sentiment

In [ ]:
# Get running count of tickers mentioned (# of times mentioned) and with average sentiment
for index, row in ticker_sentiment.iterrows():
    ticker_abbrev = row[0]
    total_count = row[1]
    total_sentiment = row[2]
    for i, r in combined_df.iterrows():
        # Get column with tickers found
        ticker_set = set(r[15])
        post_sentiment = r[26]
        if ticker_abbrev in ticker_set:
            total_count += 1
            total_sentiment += post_sentiment
    ticker_sentiment.at[index, "Total_Count"] = total_count
    ticker_sentiment.at[index, "Total_Sentiment"] = total_sentiment

In [ ]:
final_sentiment_results = ticker_sentiment.loc[ticker_sentiment['Total_Count'] != 0]

In [ ]:
final_sentiment_results = final_sentiment_results.reset_index(drop=True)

In [ ]:
final_sentiment_results

In [ ]:
final_sentiment_results["Average_Sentiment"] = final_sentiment_results["Total_Count"] / final_sentiment_results["Total_Sentiment"]

In [ ]:
final_sentiment_results

In [ ]:
final_sentiment_results['Average_Sentiment'].unique()

In [ ]:
final_sentiment_results['sentiment_label'] = "Neutral"
final_sentiment_results.loc[final_sentiment_results['Average_Sentiment'] > 0.2, 'sentiment_label'] = "Bullish"
final_sentiment_results.loc[final_sentiment_results['Average_Sentiment'] < -0.2, 'sentiment_label'] = "Bearish"

In [ ]:
# Add "today's price change" to each ticker found - total count, average sentiment, today's price change
# Include graph for visuals
import yfinance as yf
from datetime import date

In [ ]:
todays_date = date.today()
todays_date

In [ ]:
final_sentiment_results["Price_Change"] = ""
final_sentiment_results["Date"] = ""
for index, row in final_sentiment_results.iterrows():
    try:
        df = yf.download(row[0], start=todays_date)
        date = df.index[0]
        close_price = df["Close"].values[0]
        open_price = df["Open"].values[0]
        percentage_change = round((((close_price - open_price) / open_price) * 100), 2)
        final_sentiment_results.at[index, "Price_Change"] = f'{percentage_change}%'
        final_sentiment_results.at[index, "Date"] = date
    except:
        print("Data not found")
        final_sentiment_results.at[index, "Price_Change"] = "Ticker unavailable"
        final_sentiment_results.at[index, "Date"] = date

In [ ]:
final_sentiment_results

# Test database connection and process

In [ ]:
# Import SQL Alchemy
from sqlalchemy import create_engine

# Import datetime
from datetime import datetime

# Import and establish Base for which classes will be constructed 
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, Float

In [ ]:
# Create the Ticker Sentiment class
class Ticker_Sentiment(Base):
    __tablename__ = 'ticker_sentiment'
    id = Column(Integer, primary_key=True)
    ticker = Column(String(255))
    date = Column(String(255))
    count = Column(Integer)
    sentiment = Column(String)
    percent_change = Column(Float)

In [ ]:
# Create a connection to a SQLite database
engine = create_engine('sqlite:///reddit_sentiment.db')

In [ ]:
# Create the ticker_sentiment table within the database
Base.metadata.create_all(engine)

In [ ]:
# Push the objects made and query the server
from sqlalchemy.orm import Session
session = Session(bind=engine)

In [ ]:
sql_df = final_sentiment_results[["Ticker", "Date", "Total_Count", "sentiment_label", "Price_Change"]]

In [ ]:
sql_df = sql_df.rename(columns={"Ticker":"ticker", "Date":"date", "Total_Count":"count", "sentiment_label":"sentiment", "Price_Change":"percent_change"})

In [ ]:
sql_df

In [ ]:
sql_df.to_sql('ticker_sentiment', con=engine, if_exists='append', index=False)

In [ ]:
from sqlalchemy.ext.automap import automap_base
# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save reference to the table
sentiment = Base.classes.ticker_sentiment

In [ ]:
session = Session(engine)

results = session.query(sentiment.ticker).all()

session.close()

In [ ]:
import numpy as np
sentiment = list(np.ravel(results))

In [ ]:
print(sentiment)